#!/usr/bin/env bash
# ───────────────────────────────────────────────────
# ClawSynapse + Hermes Docker Entrypoint
# 1. 配置 hermes 环境变量 (.env)
# 2. 首次 init 时调用 clawsynapse init (含 SKILL.md 部署)
# 3. 启动 clawsynapsed
# ───────────────────────────────────────────────────
set -e

# These must be exported: the python heredocs below (hermes yaml config,
# ensure_api_server_env) read them from os.environ. Without export they are
# shell-local and invisible to the child python process, which silently
# skips writing API_SERVER_* — leaving the gateway API server disabled and
# the /health probe failing in a restart loop.
export CLAWSYNAPSE_CONFIG="${CLAWSYNAPSE_CONFIG:-/root/.clawsynapse/config.yaml}"
export HERMES_HOME="${HERMES_HOME:-/root/.hermes}"
export HERMES_SKILL_DIR="${HERMES_SKILL_DIR:-$HERMES_HOME/skills/clawsynapse}"
export SKILL_SRC="${SKILL_SRC:-/usr/local/share/clawsynapse/SKILL.md}"
export HERMES_ENV_FILE="$HERMES_HOME/.env"

# In Docker, the API must bind to all interfaces and match the exposed port.
CLAWSYNAPSE_API_LISTEN="${CLAWSYNAPSE_API_LISTEN:-0.0.0.0:18080}"

log() { echo "[entrypoint] $*"; }

# ─────────────────────────────────────────────────
# Step 1: Set up hermes .env (API keys from container env)
# ─────────────────────────────────────────────────
mkdir -p "$HERMES_HOME"

if [ ! -f "$HERMES_ENV_FILE" ]; then
    log "Creating hermes .env from container environment variables..."
    cat > "$HERMES_ENV_FILE" << 'HERMES_HEADER'
# Hermes Agent Environment — auto-generated by docker-entrypoint
# Add more vars via container environment or edit this file (persisted in volume)
HERMES_HEADER

    # Map known env vars → hermes .env
    declare -A ENV_MAP=(
        # TokenFlow (custom OpenAI-compatible, default)
        ["TOKENFLOW_API_KEY"]="$TOKENFLOW_API_KEY"
        ["TOKENFLOW_BASE_URL"]="$TOKENFLOW_BASE_URL"
        # Other providers
        ["DEEPSEEK_API_KEY"]="$DEEPSEEK_API_KEY"
        ["DEEPSEEK_BASE_URL"]="$DEEPSEEK_BASE_URL"
        ["OPENROUTER_API_KEY"]="$OPENROUTER_API_KEY"
        ["OPENAI_API_KEY"]="$OPENAI_API_KEY"
        ["GOOGLE_API_KEY"]="$GOOGLE_API_KEY"
        ["GEMINI_API_KEY"]="$GEMINI_API_KEY"
        ["NOVITA_API_KEY"]="$NOVITA_API_KEY"
        ["NOVITA_BASE_URL"]="$NOVITA_BASE_URL"
        ["OLLAMA_API_KEY"]="$OLLAMA_API_KEY"
    )

    for var in "${!ENV_MAP[@]}"; do
        if [ -n "${ENV_MAP[$var]}" ]; then
            echo "$var=${ENV_MAP[$var]}" >> "$HERMES_ENV_FILE"
        fi
    done

    # TokenFlow alias: also write as OPENAI_API_KEY so hermes picks it up
    # (hermes looks for OPENAI_API_KEY when provider = openai)
    if [ -n "$TOKENFLOW_API_KEY" ]; then
        echo "OPENAI_API_KEY=$TOKENFLOW_API_KEY" >> "$HERMES_ENV_FILE"
        log "  TokenFlow key aliased as OPENAI_API_KEY for hermes compatibility"
    fi

    chmod 600 "$HERMES_ENV_FILE"
    log "Wrote $HERMES_ENV_FILE"
else
    log "Hermes .env exists — preserving existing config."
fi

# ─────────────────────────────────────────────────
# Step 1b: Set hermes model config (config.yaml)
#   Uses Python + PyYAML for robust multi-line editing.
#
#   Custom provider mode (recommended):
#     HERMES_CUSTOM_PROVIDER_NAME=tokenflow
#     HERMES_CUSTOM_PROVIDER_BASE_URL=http://...
#     HERMES_CUSTOM_PROVIDER_API_KEY=sk-...
#     HERMES_CUSTOM_PROVIDER_MODEL=qwen36
#     If API_KEY is empty, falls back to TOKENFLOW_API_KEY.
#
#   Legacy provider mode (fallback):
#     HERMES_MODEL, HERMES_PROVIDER, HERMES_BASE_URL
# ─────────────────────────────────────────────────
HERMES_CONFIG="$HERMES_HOME/config.yaml"

configure_hermes_yaml() {
    python3 - << 'PY'
import os, sys, yaml

class IndentedDumper(yaml.SafeDumper):
    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)

config_path = os.environ.get("HERMES_CONFIG", "/root/.hermes/config.yaml")

# Custom provider env
name = os.environ.get("HERMES_CUSTOM_PROVIDER_NAME", "").strip()
base_url = os.environ.get("HERMES_CUSTOM_PROVIDER_BASE_URL", "").strip()
api_key = os.environ.get("HERMES_CUSTOM_PROVIDER_API_KEY", "").strip()
model = os.environ.get("HERMES_CUSTOM_PROVIDER_MODEL", "").strip()

# Fallback API key to TokenFlow key
if not api_key:
    api_key = os.environ.get("TOKENFLOW_API_KEY", "").strip()

# Legacy env
legacy_model = os.environ.get("HERMES_MODEL", "").strip()
legacy_provider = os.environ.get("HERMES_PROVIDER", "").strip()
legacy_base = os.environ.get("HERMES_BASE_URL", "").strip()

if not os.path.exists(config_path):
    # 首次启动（hermes-data 卷挂载后卷内尚无 config.yaml）时，不要跳过：
    # 先写入最小骨架，再走下方统一合并逻辑补全 provider/model/skills。
    # 旧逻辑此处 sys.exit(0) 会导致 provider 永不写入，gateway 虽健康却无可用模型。
    try:
        with open(config_path, "w", encoding="utf-8") as f:
            yaml.safe_dump({"model": {}}, f, Dumper=IndentedDumper,
                           sort_keys=False, default_flow_style=False, allow_unicode=True)
        print(f"[entrypoint] {config_path} not found — created initial skeleton.")
    except OSError as e:
        print(f"WARN: cannot create {config_path}: {e}")
        sys.exit(0)

with open(config_path, "r", encoding="utf-8") as f:
    config = yaml.safe_load(f) or {}

if "model" not in config or config["model"] is None:
    config["model"] = {}
model_section = config["model"]

if name:
    print(f"[entrypoint] Configuring custom provider: {name}")

    if "custom_providers" not in config or config["custom_providers"] is None:
        config["custom_providers"] = []
    providers = config["custom_providers"]
    if not isinstance(providers, list):
        providers = []
        config["custom_providers"] = providers

    provider_entry = None
    for p in providers:
        if isinstance(p, dict) and p.get("name") == name:
            provider_entry = p
            break

    if provider_entry is None:
        provider_entry = {}
        providers.append(provider_entry)

    provider_entry["name"] = name
    if base_url:
        provider_entry["base_url"] = base_url
    if api_key:
        provider_entry["api_key"] = api_key
    if model:
        provider_entry["model"] = model

    if model:
        model_section["default"] = model
        print(f"[entrypoint]   model.default = {model}")
    model_section["provider"] = name
    print(f"[entrypoint]   model.provider = {name}")
    # base_url lives on the provider entry now
    model_section.pop("base_url", None)
else:
    print("[entrypoint] Configuring hermes model (legacy provider mode)...")
    if legacy_model:
        model_section["default"] = legacy_model
        print(f"[entrypoint]   model.default = {legacy_model}")
    if legacy_provider:
        model_section["provider"] = legacy_provider
        print(f"[entrypoint]   model.provider = {legacy_provider}")
    if legacy_base:
        model_section["base_url"] = legacy_base
        print(f"[entrypoint]   model.base_url = {legacy_base}")

# Gateway: auto-approve (yolo) so task runs never block on tool approvals.
if "approvals" not in config or config["approvals"] is None:
    config["approvals"] = {}
config["approvals"]["mode"] = "off"

# Skills are loaded at the profile level (the gateway API has no per-request
# -s flag). Mount only the skills for this agent's role.
role = os.environ.get("CLAWSYNAPSE_AGENT_ROLE", "").strip().lower()
skills_base = os.environ.get("HERMES_SKILL_DIR", "/root/.hermes/skills/clawsynapse")
skills_root = os.path.dirname(skills_base)
role_skills = {
    "pm": ["clawsynapse", "tm-task-plan"],
    "executor": ["clawsynapse", "tm-task-exec"],
}
names = role_skills.get(role, ["clawsynapse"])
config["external_dirs"] = [os.path.join(skills_root, n) for n in names]
print(f"[entrypoint] external_dirs = {config['external_dirs']}")

with open(config_path, "w", encoding="utf-8") as f:
    yaml.dump(config, f, Dumper=IndentedDumper, default_flow_style=False,
              sort_keys=False, allow_unicode=True, indent=2)

print("[entrypoint] Hermes config.yaml updated.")
PY
}

configure_hermes_yaml

# ─────────────────────────────────────────────────
# Step 1c: Ensure Gateway API Server config in .env (idempotent)
# ─────────────────────────────────────────────────
ensure_api_server_env() {
    python3 - << 'PY'
import os, sys
p = os.environ.get("HERMES_ENV_FILE")
if not p or not os.path.exists(p):
    sys.exit(0)
with open(p) as f:
    lines = f.read().splitlines()
present = {l.split("=", 1)[0].strip(): i for i, l in enumerate(lines) if "=" in l}
changed = False

def ensure(key, val):
    global changed, lines, present
    if key in present:
        idx = present[key]
        if lines[idx].split("=", 1)[1].strip() != val:
            lines[idx] = f"{key}={val}"
            changed = True
    else:
        lines.append(f"{key}={val}")
        present[key] = len(lines) - 1
        changed = True

ensure("API_SERVER_ENABLED", "true")
ensure("API_SERVER_HOST", "127.0.0.1")
ensure("API_SERVER_PORT", "8642")
gw_key = os.environ.get("HERMES_GATEWAY_KEY", "").strip()
if gw_key:
    ensure("API_SERVER_KEY", gw_key)
elif "API_SERVER_KEY" not in present:
    import subprocess
    ensure("API_SERVER_KEY", subprocess.check_output(["openssl", "rand", "-hex", "16"]).decode().strip())

if changed:
    with open(p, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("[entrypoint] Hermes .env API_SERVER config ensured.")
PY
}
ensure_api_server_env

# ─────────────────────────────────────────────────
# Step 2: First-time clawsynapse init
# ─────────────────────────────────────────────────
if [ ! -f "$CLAWSYNAPSE_CONFIG" ]; then
    log "First run — initializing clawsynapse with hermes adapter..."

    INIT_ARGS=(
        --agent-adapter hermes
        --local-api-addr "$CLAWSYNAPSE_API_LISTEN"
        --deliverable-prefixes chat,task,todo
        --non-interactive
        --overwrite
    )

    [ -n "$CLAWSYNAPSE_NODE_ID" ]     && INIT_ARGS+=(--node-id "$CLAWSYNAPSE_NODE_ID")
    [ -n "$CLAWSYNAPSE_NODE_KEY" ]    && INIT_ARGS+=(--node-key "$CLAWSYNAPSE_NODE_KEY")
    [ -n "$CLAWSYNAPSE_AGENT_ROLE" ]  && INIT_ARGS+=(--agent-role "$CLAWSYNAPSE_AGENT_ROLE")

    clawsynapse init "${INIT_ARGS[@]}"

    # init --agent-adapter hermes 会自动部署 SKILL.md 到 ~/.hermes/skills/clawsynapse/
    # 但作为 belt & suspenders，也手动确保一下
    if [ ! -f "$HERMES_SKILL_DIR/SKILL.md" ] && [ -f "$SKILL_SRC" ]; then
        mkdir -p "$HERMES_SKILL_DIR"
        cp "$SKILL_SRC" "$HERMES_SKILL_DIR/SKILL.md"
        log "Deployed SKILL.md → $HERMES_SKILL_DIR/ (fallback)"
    fi

    log "Init complete."
else
    log "Config found at $CLAWSYNAPSE_CONFIG — skipping init."
fi

# ─────────────────────────────────────────────────
# Step 3: Ensure SKILL.md is deployed (post-init fixup)
# ─────────────────────────────────────────────────
if [ ! -f "$HERMES_SKILL_DIR/SKILL.md" ] && [ -f "$SKILL_SRC" ]; then
    mkdir -p "$HERMES_SKILL_DIR"
    cp "$SKILL_SRC" "$HERMES_SKILL_DIR/SKILL.md"
    log "Deployed SKILL.md → $HERMES_SKILL_DIR/ (post-init fixup)"
fi

# ─────────────────────────────────────────────────
# Step 4: Runtime config overrides from env
# ─────────────────────────────────────────────────
if [ -f "$CLAWSYNAPSE_CONFIG" ]; then
    sed -i "s|^localApiAddr:.*|localApiAddr: ${CLAWSYNAPSE_API_LISTEN}|" "$CLAWSYNAPSE_CONFIG" 2>/dev/null || true
    sed -i "s|^logFilePath:.*|logFilePath: \"\"|" "$CLAWSYNAPSE_CONFIG" 2>/dev/null || true
fi

# ─────────────────────────────────────────────────
# Step 4.5: Start Hermes Gateway (API Server) in background, wait for /health
# ─────────────────────────────────────────────────
export HERMES_HOME
GATEWAY_PORT="${HERMES_GATEWAY_PORT:-8642}"
GATEWAY_HOST="${HERMES_GATEWAY_HOST:-127.0.0.1}"
export HERMES_HEALTH_URL="http://${GATEWAY_HOST}:${GATEWAY_PORT}/health"

# Preflight: the API Server platform needs aiohttp inside Hermes's venv.
# If it's missing the gateway will "run" but nothing listens on 8642, and the
# adapter health check fails with no obvious reason. Surface it early.
HERMES_BIN="$(command -v hermes 2>/dev/null || true)"
if [ -n "$HERMES_BIN" ]; then
    HERMES_REAL="$(readlink -f "$HERMES_BIN" 2>/dev/null || echo "$HERMES_BIN")"
    HERMES_VENV_PY="$(dirname "$HERMES_REAL")/python"
    if [ -x "$HERMES_VENV_PY" ]; then
        if "$HERMES_VENV_PY" -c "import aiohttp" 2>/dev/null; then
            log "Preflight OK: aiohttp available in hermes venv ($HERMES_VENV_PY)."
        else
            log "WARN: aiohttp NOT importable in hermes venv ($HERMES_VENV_PY) — API Server may fail to start on 8642."
        fi
    fi
fi

log "Starting hermes gateway (API server) on ${GATEWAY_HOST}:${GATEWAY_PORT}..."
hermes gateway run > /var/log/hermes-gateway.log 2>&1 &
GATEWAY_PID=$!

health_ok() {
    python3 - << 'PY'
import os, urllib.request, sys
url = os.environ.get("HERMES_HEALTH_URL", "")
try:
    with urllib.request.urlopen(url, timeout=2) as r:
        sys.exit(0 if r.status == 200 else 1)
except Exception:
    sys.exit(1)
PY
}

for i in $(seq 1 60); do
    if health_ok; then
        log "Hermes gateway is healthy."
        break
    fi
    if ! kill -0 "$GATEWAY_PID" 2>/dev/null; then
        log "ERROR: hermes gateway exited prematurely. Last log lines:"
        tail -n 20 /var/log/hermes-gateway.log 2>/dev/null || true
        exit 1
    fi
    sleep 1
done
if ! health_ok; then
    log "ERROR: hermes gateway not healthy after 60s — aborting container. Last gateway log lines:"
    tail -n 30 /var/log/hermes-gateway.log 2>/dev/null || true
    exit 1
fi

# ─────────────────────────────────────────────────
# Step 5: Start clawsynapse daemon
# ─────────────────────────────────────────────────
log "Starting clawsynapsed..."
exec clawsynapsed start
