#!/usr/bin/env bash
# ───────────────────────────────────────────────────
# ClawSynapse + Hermes Docker Entrypoint
# 1. 配置 hermes 环境变量 (.env)
# 2. 首次 init 时调用 clawsynapse init (含 SKILL.md 部署)
# 3. 启动 clawsynapsed
# ───────────────────────────────────────────────────
set -e

CLAWSYNAPSE_CONFIG="${CLAWSYNAPSE_CONFIG:-/root/.clawsynapse/config.yaml}"
HERMES_HOME="${HERMES_HOME:-/root/.hermes}"
HERMES_SKILL_DIR="${HERMES_SKILL_DIR:-$HERMES_HOME/skills/clawsynapse}"
SKILL_SRC="${SKILL_SRC:-/usr/local/share/clawsynapse/SKILL.md}"
HERMES_ENV_FILE="$HERMES_HOME/.env"

# In Docker, the API must bind to all interfaces and match the exposed port.
CLAWSYNAPSE_API_LISTEN="${CLAWSYNAPSE_API_LISTEN:-0.0.0.0:18080}"

log() { echo "[entrypoint] $*"; }

# ─────────────────────────────────────────────────
# Step 1: Set up hermes .env (API keys from container env)
# ─────────────────────────────────────────────────
mkdir -p "$HERMES_HOME"

if [ ! -f "$HERMES_ENV_FILE" ]; then
    log "Creating hermes .env from container environment variables..."
    cat > "$HERMES_ENV_FILE" << 'HERMES_HEADER'
# Hermes Agent Environment — auto-generated by docker-entrypoint
# Add more vars via container environment or edit this file (persisted in volume)
HERMES_HEADER

    # Map known env vars → hermes .env
    declare -A ENV_MAP=(
        # TokenFlow (custom OpenAI-compatible, default)
        ["TOKENFLOW_API_KEY"]="$TOKENFLOW_API_KEY"
        ["TOKENFLOW_BASE_URL"]="$TOKENFLOW_BASE_URL"
        # Other providers
        ["DEEPSEEK_API_KEY"]="$DEEPSEEK_API_KEY"
        ["DEEPSEEK_BASE_URL"]="$DEEPSEEK_BASE_URL"
        ["OPENROUTER_API_KEY"]="$OPENROUTER_API_KEY"
        ["OPENAI_API_KEY"]="$OPENAI_API_KEY"
        ["GOOGLE_API_KEY"]="$GOOGLE_API_KEY"
        ["GEMINI_API_KEY"]="$GEMINI_API_KEY"
        ["NOVITA_API_KEY"]="$NOVITA_API_KEY"
        ["NOVITA_BASE_URL"]="$NOVITA_BASE_URL"
        ["OLLAMA_API_KEY"]="$OLLAMA_API_KEY"
    )

    for var in "${!ENV_MAP[@]}"; do
        if [ -n "${ENV_MAP[$var]}" ]; then
            echo "$var=${ENV_MAP[$var]}" >> "$HERMES_ENV_FILE"
        fi
    done

    # TokenFlow alias: also write as OPENAI_API_KEY so hermes picks it up
    # (hermes looks for OPENAI_API_KEY when provider = openai)
    if [ -n "$TOKENFLOW_API_KEY" ]; then
        echo "OPENAI_API_KEY=$TOKENFLOW_API_KEY" >> "$HERMES_ENV_FILE"
        log "  TokenFlow key aliased as OPENAI_API_KEY for hermes compatibility"
    fi

    chmod 600 "$HERMES_ENV_FILE"
    log "Wrote $HERMES_ENV_FILE"
else
    log "Hermes .env exists — preserving existing config."
fi

# ─────────────────────────────────────────────────
# Step 1b: Set hermes model config (config.yaml)
#   Uses Python + PyYAML for robust multi-line editing.
#
#   Custom provider mode (recommended):
#     HERMES_CUSTOM_PROVIDER_NAME=tokenflow
#     HERMES_CUSTOM_PROVIDER_BASE_URL=http://...
#     HERMES_CUSTOM_PROVIDER_API_KEY=sk-...
#     HERMES_CUSTOM_PROVIDER_MODEL=qwen36
#     If API_KEY is empty, falls back to TOKENFLOW_API_KEY.
#
#   Legacy provider mode (fallback):
#     HERMES_MODEL, HERMES_PROVIDER, HERMES_BASE_URL
# ─────────────────────────────────────────────────
HERMES_CONFIG="$HERMES_HOME/config.yaml"

configure_hermes_yaml() {
    python3 - << 'PY'
import os, sys, yaml

class IndentedDumper(yaml.SafeDumper):
    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)

config_path = os.environ.get("HERMES_CONFIG", "/root/.hermes/config.yaml")

# Custom provider env
name = os.environ.get("HERMES_CUSTOM_PROVIDER_NAME", "").strip()
base_url = os.environ.get("HERMES_CUSTOM_PROVIDER_BASE_URL", "").strip()
api_key = os.environ.get("HERMES_CUSTOM_PROVIDER_API_KEY", "").strip()
model = os.environ.get("HERMES_CUSTOM_PROVIDER_MODEL", "").strip()

# Fallback API key to TokenFlow key
if not api_key:
    api_key = os.environ.get("TOKENFLOW_API_KEY", "").strip()

# Legacy env
legacy_model = os.environ.get("HERMES_MODEL", "").strip()
legacy_provider = os.environ.get("HERMES_PROVIDER", "").strip()
legacy_base = os.environ.get("HERMES_BASE_URL", "").strip()

if not os.path.exists(config_path):
    print(f"WARN: {config_path} not found yet — model config skipped.")
    print("      Run 'hermes setup' inside the container after first start.")
    sys.exit(0)

with open(config_path, "r", encoding="utf-8") as f:
    config = yaml.safe_load(f) or {}

if "model" not in config or config["model"] is None:
    config["model"] = {}
model_section = config["model"]

if name:
    print(f"[entrypoint] Configuring custom provider: {name}")

    if "custom_providers" not in config or config["custom_providers"] is None:
        config["custom_providers"] = []
    providers = config["custom_providers"]
    if not isinstance(providers, list):
        providers = []
        config["custom_providers"] = providers

    provider_entry = None
    for p in providers:
        if isinstance(p, dict) and p.get("name") == name:
            provider_entry = p
            break

    if provider_entry is None:
        provider_entry = {}
        providers.append(provider_entry)

    provider_entry["name"] = name
    if base_url:
        provider_entry["base_url"] = base_url
    if api_key:
        provider_entry["api_key"] = api_key
    if model:
        provider_entry["model"] = model

    if model:
        model_section["default"] = model
        print(f"[entrypoint]   model.default = {model}")
    model_section["provider"] = name
    print(f"[entrypoint]   model.provider = {name}")
    # base_url lives on the provider entry now
    model_section.pop("base_url", None)
else:
    print("[entrypoint] Configuring hermes model (legacy provider mode)...")
    if legacy_model:
        model_section["default"] = legacy_model
        print(f"[entrypoint]   model.default = {legacy_model}")
    if legacy_provider:
        model_section["provider"] = legacy_provider
        print(f"[entrypoint]   model.provider = {legacy_provider}")
    if legacy_base:
        model_section["base_url"] = legacy_base
        print(f"[entrypoint]   model.base_url = {legacy_base}")

with open(config_path, "w", encoding="utf-8") as f:
    yaml.dump(config, f, Dumper=IndentedDumper, default_flow_style=False,
              sort_keys=False, allow_unicode=True, indent=2)

print("[entrypoint] Hermes config.yaml updated.")
PY
}

configure_hermes_yaml

# ─────────────────────────────────────────────────
# Step 2: First-time clawsynapse init
# ─────────────────────────────────────────────────
if [ ! -f "$CLAWSYNAPSE_CONFIG" ]; then
    log "First run — initializing clawsynapse with hermes adapter..."

    INIT_ARGS=(
        --agent-adapter hermes
        --local-api-addr "$CLAWSYNAPSE_API_LISTEN"
        --deliverable-prefixes chat,task,todo
        --non-interactive
        --overwrite
    )

    [ -n "$CLAWSYNAPSE_NODE_ID" ]     && INIT_ARGS+=(--node-id "$CLAWSYNAPSE_NODE_ID")
    [ -n "$CLAWSYNAPSE_NODE_KEY" ]    && INIT_ARGS+=(--node-key "$CLAWSYNAPSE_NODE_KEY")
    [ -n "$CLAWSYNAPSE_AGENT_ROLE" ]  && INIT_ARGS+=(--agent-role "$CLAWSYNAPSE_AGENT_ROLE")

    clawsynapse init "${INIT_ARGS[@]}"

    # init --agent-adapter hermes 会自动部署 SKILL.md 到 ~/.hermes/skills/clawsynapse/
    # 但作为 belt & suspenders，也手动确保一下
    if [ ! -f "$HERMES_SKILL_DIR/SKILL.md" ] && [ -f "$SKILL_SRC" ]; then
        mkdir -p "$HERMES_SKILL_DIR"
        cp "$SKILL_SRC" "$HERMES_SKILL_DIR/SKILL.md"
        log "Deployed SKILL.md → $HERMES_SKILL_DIR/ (fallback)"
    fi

    log "Init complete."
else
    log "Config found at $CLAWSYNAPSE_CONFIG — skipping init."
fi

# ─────────────────────────────────────────────────
# Step 3: Ensure SKILL.md is deployed (post-init fixup)
# ─────────────────────────────────────────────────
if [ ! -f "$HERMES_SKILL_DIR/SKILL.md" ] && [ -f "$SKILL_SRC" ]; then
    mkdir -p "$HERMES_SKILL_DIR"
    cp "$SKILL_SRC" "$HERMES_SKILL_DIR/SKILL.md"
    log "Deployed SKILL.md → $HERMES_SKILL_DIR/ (post-init fixup)"
fi

# ─────────────────────────────────────────────────
# Step 4: Runtime config overrides from env
# ─────────────────────────────────────────────────
if [ -f "$CLAWSYNAPSE_CONFIG" ]; then
    sed -i "s|^localApiAddr:.*|localApiAddr: ${CLAWSYNAPSE_API_LISTEN}|" "$CLAWSYNAPSE_CONFIG" 2>/dev/null || true
    sed -i "s|^logFilePath:.*|logFilePath: \"\"|" "$CLAWSYNAPSE_CONFIG" 2>/dev/null || true
fi

# ─────────────────────────────────────────────────
# Step 5: Start clawsynapse daemon
# ─────────────────────────────────────────────────
log "Starting clawsynapsed..."
exec clawsynapsed start
