#!/usr/bin/env bash
# ───────────────────────────────────────────────────
# ClawSynapse + Hermes Docker Entrypoint
# 1. 配置 hermes 环境变量 (.env)
# 2. 首次 init 时调用 clawsynapse init (含 SKILL.md 部署)
# 3. 启动 clawsynapsed
# ───────────────────────────────────────────────────
set -e

CLAWSYNAPSE_CONFIG="${CLAWSYNAPSE_CONFIG:-/root/.clawsynapse/config.yaml}"
HERMES_HOME="${HERMES_HOME:-/root/.hermes}"
HERMES_SKILL_DIR="${HERMES_SKILL_DIR:-$HERMES_HOME/skills/clawsynapse}"
SKILL_SRC="${SKILL_SRC:-/usr/local/share/clawsynapse/SKILL.md}"
HERMES_ENV_FILE="$HERMES_HOME/.env"

log() { echo "[entrypoint] $*"; }

# ─────────────────────────────────────────────────
# Step 1: Set up hermes .env (API keys from container env)
# ─────────────────────────────────────────────────
mkdir -p "$HERMES_HOME"

if [ ! -f "$HERMES_ENV_FILE" ]; then
    log "Creating hermes .env from container environment variables..."
    cat > "$HERMES_ENV_FILE" << 'HERMES_HEADER'
# Hermes Agent Environment — auto-generated by docker-entrypoint
# Add more vars via container environment or edit this file (persisted in volume)
HERMES_HEADER

    # Map known env vars → hermes .env
    # Add more mappings below as needed
    declare -A ENV_MAP=(
        ["DEEPSEEK_API_KEY"]="$DEEPSEEK_API_KEY"
        ["DEEPSEEK_BASE_URL"]="$DEEPSEEK_BASE_URL"
        ["OPENROUTER_API_KEY"]="$OPENROUTER_API_KEY"
        ["OPENAI_API_KEY"]="$OPENAI_API_KEY"
        ["GOOGLE_API_KEY"]="$GOOGLE_API_KEY"
        ["GEMINI_API_KEY"]="$GEMINI_API_KEY"
        ["NOVITA_API_KEY"]="$NOVITA_API_KEY"
        ["OLLAMA_API_KEY"]="$OLLAMA_API_KEY"
    )

    for var in "${!ENV_MAP[@]}"; do
        if [ -n "${ENV_MAP[$var]}" ]; then
            echo "$var=${ENV_MAP[$var]}" >> "$HERMES_ENV_FILE"
        fi
    done

    chmod 600 "$HERMES_ENV_FILE"
    log "Wrote $HERMES_ENV_FILE"
else
    log "Hermes .env exists — preserving existing config."
fi

# ─────────────────────────────────────────────────
# Step 1b: Set hermes model config (config.yaml)
#   HERMES_MODEL     — model name (e.g. gpt-4o, claude-sonnet-4-20250514)
#   HERMES_PROVIDER  — provider key (openai, anthropic, google, deepseek, openrouter, novita, ollama)
#   HERMES_BASE_URL  — optional custom base URL
# ─────────────────────────────────────────────────
HERMES_CONFIG="$HERMES_HOME/config.yaml"

if [ -n "$HERMES_MODEL" ] || [ -n "$HERMES_PROVIDER" ] || [ -n "$HERMES_BASE_URL" ]; then
    # Wait for config.yaml to exist (hermes install creates it)
    if [ -f "$HERMES_CONFIG" ]; then
        log "Configuring hermes model in config.yaml..."
        if [ -n "$HERMES_MODEL" ]; then
            sed -i "s|^  default:.*|  default: ${HERMES_MODEL}|" "$HERMES_CONFIG"
            log "  model.default = $HERMES_MODEL"
        fi
        if [ -n "$HERMES_PROVIDER" ]; then
            sed -i "s|^  provider:.*|  provider: ${HERMES_PROVIDER}|" "$HERMES_CONFIG"
            log "  model.provider = $HERMES_PROVIDER"
        fi
        if [ -n "$HERMES_BASE_URL" ]; then
            sed -i "s|^  base_url:.*|  base_url: ${HERMES_BASE_URL}|" "$HERMES_CONFIG"
            log "  model.base_url = $HERMES_BASE_URL"
        fi
    else
        log "WARN: $HERMES_CONFIG not found yet — model config skipped."
        log "      Run 'hermes setup' inside the container after first start."
    fi
fi

# ─────────────────────────────────────────────────
# Step 2: First-time clawsynapse init
# ─────────────────────────────────────────────────
if [ ! -f "$CLAWSYNAPSE_CONFIG" ]; then
    log "First run — initializing clawsynapse with hermes adapter..."

    INIT_ARGS=(--agent-adapter hermes)

    [ -n "$CLAWSYNAPSE_NODE_ID" ]     && INIT_ARGS+=(--node-id "$CLAWSYNAPSE_NODE_ID")
    [ -n "$CLAWSYNAPSE_NODE_KEY" ]    && INIT_ARGS+=(--node-key "$CLAWSYNAPSE_NODE_KEY")
    [ -n "$CLAWSYNAPSE_AGENT_ROLE" ]  && INIT_ARGS+=(--agent-role "$CLAWSYNAPSE_AGENT_ROLE")
    [ -n "$CLAWSYNAPSE_API_LISTEN" ]  && INIT_ARGS+=(--api-listen "$CLAWSYNAPSE_API_LISTEN")

    clawsynapse init "${INIT_ARGS[@]}"

    # init --agent-adapter hermes 会自动部署 SKILL.md 到 ~/.hermes/skills/clawsynapse/
    # 但作为 belt & suspenders，也手动确保一下
    if [ ! -f "$HERMES_SKILL_DIR/SKILL.md" ] && [ -f "$SKILL_SRC" ]; then
        mkdir -p "$HERMES_SKILL_DIR"
        cp "$SKILL_SRC" "$HERMES_SKILL_DIR/SKILL.md"
        log "Deployed SKILL.md → $HERMES_SKILL_DIR/ (fallback)"
    fi

    log "Init complete."
else
    log "Config found at $CLAWSYNAPSE_CONFIG — skipping init."
fi

# ─────────────────────────────────────────────────
# Step 3: Ensure SKILL.md is deployed (post-init fixup)
# ─────────────────────────────────────────────────
if [ ! -f "$HERMES_SKILL_DIR/SKILL.md" ] && [ -f "$SKILL_SRC" ]; then
    mkdir -p "$HERMES_SKILL_DIR"
    cp "$SKILL_SRC" "$HERMES_SKILL_DIR/SKILL.md"
    log "Deployed SKILL.md → $HERMES_SKILL_DIR/ (post-init fixup)"
fi

# ─────────────────────────────────────────────────
# Step 4: Runtime config overrides from env
# ─────────────────────────────────────────────────
if [ -n "$CLAWSYNAPSE_API_LISTEN" ] && [ -f "$CLAWSYNAPSE_CONFIG" ]; then
    sed -i "s|^apiListen:.*|apiListen: ${CLAWSYNAPSE_API_LISTEN}|" "$CLAWSYNAPSE_CONFIG" 2>/dev/null || true
fi

# ─────────────────────────────────────────────────
# Step 5: Start clawsynapse daemon
# ─────────────────────────────────────────────────
log "Starting clawsynapsed..."
exec clawsynapsed start
